export interface HeroPreset {
  id: string;
  niche: string;
  variationName?: string;
  title: string;
  subtitle: string;
  badge: string;
  badgeIcon?: string;
  primaryButton: string;
  secondaryButton: string;
  bgImage: string;
  bgColor?: string;
  bgType: "color" | "image";
  titleColor?: string;
  subtitleColor?: string;
  badgeColor?: string;
  badgeTextColor?: string;
  primaryButtonColor?: string;
  primaryButtonTextColor?: string;
  secondaryButtonColor?: string;
  secondaryButtonTextColor?: string;
  fontFamily?: "sans" | "serif" | "montserrat" | "lora" | "syne" | "bebas" | "space" | "poppins" | "cinzel";
  titleSize?: "sm" | "md" | "lg" | "xl";
}

export const heroPresets: HeroPreset[] = [
  // 1. STUDIO DE SOBRANCELHA
  {
    id: "sobrancelha-1",
    niche: "Studio de Sobrancelha",
    variationName: "Elegante & Minimalista",
    title: "Olhar Marcante e Natural",
    subtitle: "Especialistas em design de sobrancelhas e micropigmentação para realçar sua beleza única.",
    badge: "Design Premium",
    badgeIcon: "Sparkles",
    primaryButton: "Agendar Agora",
    secondaryButton: "Ver Galeria",
    bgImage: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#d946ef",
    badgeColor: "#fdf4ff",
    badgeTextColor: "#a21caf",
    fontFamily: "lora",
    titleSize: "md"
  },
  {
    id: "sobrancelha-2",
    niche: "Studio de Sobrancelha",
    variationName: "Moderno & Vibrante",
    title: "Transforme seu Olhar hoje",
    subtitle: "Técnicas avançadas de Brow Lamination e Design com Henna. Realce sua expressão facial.",
    badge: "Nova Tendência",
    badgeIcon: "Star",
    primaryButton: "Quero Agendar",
    secondaryButton: "Preços",
    bgImage: "https://images.unsplash.com/photo-1560869713-7d0a29430803?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#86198f",
    badgeColor: "#fae8ff",
    badgeTextColor: "#701a75",
    fontFamily: "montserrat",
    titleSize: "lg"
  },
  {
    id: "sobrancelha-3",
    niche: "Studio de Sobrancelha",
    variationName: "Luxo & Sofisticação",
    title: "A Perfeição em Cada Traço",
    subtitle: "Onde a arte encontra a beleza. Micropigmentação realista e design personalizado de alto padrão.",
    badge: "VIP Experience",
    badgeIcon: "Crown",
    primaryButton: "Agendamento VIP",
    secondaryButton: "Nossos Cases",
    bgImage: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#701a75",
    badgeColor: "#fdf4ff",
    badgeTextColor: "#701a75",
    fontFamily: "serif",
    titleSize: "xl"
  },

  // 2. MANICURE E PEDICURE
  {
    id: "manicure-1",
    niche: "Manicure e Pedicure",
    variationName: "Delicado & Feminino",
    title: "Suas Mãos Merecem esse Cuidado",
    subtitle: "Unhas impecáveis com os melhores produtos e técnicas de esmaltação e alongamento.",
    badge: "Cuidado e Higiene",
    badgeIcon: "Heart",
    primaryButton: "Marcar Horário",
    secondaryButton: "Nossos Serviços",
    bgImage: "https://images.unsplash.com/photo-1632345033840-202d0839c6ec?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#ec4899",
    badgeColor: "#fdf2f8",
    badgeTextColor: "#be185d",
    fontFamily: "sans",
    titleSize: "md"
  },
  {
    id: "manicure-2",
    niche: "Manicure e Pedicure",
    variationName: "Luxuoso & Sofisticado",
    title: "A Arte em suas Mãos",
    subtitle: "Especialistas em Nail Art e blindagem. Experimente o luxo em cada detalhe das suas unhas.",
    badge: "Nail Art Premium",
    badgeIcon: "Gem",
    primaryButton: "Agendamento VIP",
    secondaryButton: "Inspirar-se",
    bgImage: "https://images.unsplash.com/photo-1604654894610-df490c81726a?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#9d174d",
    badgeColor: "#fdf2f8",
    badgeTextColor: "#be185d",
    fontFamily: "serif",
    titleSize: "lg"
  },
  {
    id: "manicure-3",
    niche: "Manicure e Pedicure",
    variationName: "Moderno & Bold",
    title: "Unhas que Falam por Você",
    subtitle: "Estilo urbano e cores vibrantes. Tendências mundiais em alongamento e decoração.",
    badge: "Trend Alert",
    badgeIcon: "Sparkles",
    primaryButton: "Quero Esse Estilo",
    secondaryButton: "Ver Fotos",
    bgImage: "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#db2777",
    badgeColor: "#fdf2f8",
    badgeTextColor: "#db2777",
    fontFamily: "space",
    titleSize: "xl"
  },

  // 3. CLINICAS EM GERAL
  {
    id: "clinica-1",
    niche: "Clínicas em Geral",
    variationName: "Médico & Profissional",
    title: "Sua Saúde em Boas Mãos",
    subtitle: "Equipe multidisciplinar pronta para oferecer o melhor atendimento e tecnologia médica.",
    badge: "Atendimento Humanizado",
    badgeIcon: "Award",
    primaryButton: "Agendar Consulta",
    secondaryButton: "Especialidades",
    bgImage: "https://images.unsplash.com/photo-1629909608135-ca4679237617?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#0284c7",
    badgeColor: "#f0f9ff",
    badgeTextColor: "#0369a1",
    fontFamily: "sans",
    titleSize: "md"
  },
  {
    id: "clinica-2",
    niche: "Clínicas em Geral",
    variationName: "Estética & Bem-estar",
    title: "Tecnologia a Favor da sua Autoestima",
    subtitle: "Tratamentos faciais e corporais personalizados com resultados reais e duradouros.",
    badge: "Estética Avançada",
    badgeIcon: "Sparkles",
    primaryButton: "Avaliação Gratuita",
    secondaryButton: "Ver Antes e Depois",
    bgImage: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#14b8a6",
    badgeColor: "#f0fdfa",
    badgeTextColor: "#0f766e",
    fontFamily: "lora",
    titleSize: "lg"
  },
  {
    id: "clinica-3",
    niche: "Clínicas em Geral",
    variationName: "Inovação & Futuro",
    title: "O Futuro da sua Saúde Hoje",
    subtitle: "Medicina de precisão e exames avançados em um só lugar. Rapidez e confiança no diagnóstico.",
    badge: "Tecnologia Médica",
    badgeIcon: "Gem",
    primaryButton: "Conhecer Clínica",
    secondaryButton: "Agendar Exame",
    bgImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#0369a1",
    badgeColor: "#f0f9ff",
    badgeTextColor: "#0369a1",
    fontFamily: "space",
    titleSize: "xl"
  },

  // 4. SALÕES DE BELEZA
  {
    id: "salao-beleza-1",
    niche: "Salão de Beleza",
    variationName: "Glamour & Estilo",
    title: "Sua Melhor Versão Começa Aqui",
    subtitle: "Cabelo, estética e bem-estar em um ambiente pensado para você relaxar e se renovar.",
    badge: "Salão Premium",
    badgeIcon: "Crown",
    primaryButton: "Agendar Agora",
    secondaryButton: "Serviços",
    bgImage: "https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#f43f5e",
    badgeColor: "#fff1f2",
    badgeTextColor: "#e11d48",
    fontFamily: "serif",
    titleSize: "md"
  },
  {
    id: "salao-beleza-2",
    niche: "Salão de Beleza",
    variationName: "Moderno & Urbano",
    title: "Corte, Cor e Personalidade",
    subtitle: "Tendências internacionais de coloração e corte para destacar sua identidade única.",
    badge: "Expert em Cores",
    badgeIcon: "Star",
    primaryButton: "Quero Mudar",
    secondaryButton: "Galeria",
    bgImage: "https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#be123c",
    badgeColor: "#fff1f2",
    badgeTextColor: "#9f1239",
    fontFamily: "montserrat",
    titleSize: "lg"
  },
  {
    id: "salao-beleza-3",
    niche: "Salão de Beleza",
    variationName: "Impacto & Atitude",
    title: "REINVENTE SEU VISUAL",
    subtitle: "Especialistas em mudanças radicais e tratamentos de luxo para fios saudáveis e brilhantes.",
    badge: "Top Hairstylists",
    badgeIcon: "Sparkles",
    primaryButton: "Mudar Agora",
    secondaryButton: "Nossos Produtos",
    bgImage: "https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#000000",
    badgeColor: "#ffffff",
    badgeTextColor: "#000000",
    fontFamily: "bebas",
    titleSize: "xl"
  },

  // 5. SALÕES DE CORTE MASCULINO (BARBEARIA)
  {
    id: "barbearia-1",
    niche: "Salão de Corte Masculino",
    variationName: "Clássico & Vintage",
    title: "Resgatando a Tradição",
    subtitle: "O clássico e o moderno se encontram para oferecer a melhor experiência em barba e cabelo.",
    badge: "Barba e Cabelo",
    badgeIcon: "Crown",
    primaryButton: "Agendar Corte",
    secondaryButton: "Preços",
    bgImage: "https://images.unsplash.com/photo-1503951914875-452162b0f3f1?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1f2937",
    badgeColor: "#374151",
    badgeTextColor: "#f9fafb",
    fontFamily: "serif",
    titleSize: "md"
  },
  {
    id: "barbearia-2",
    niche: "Salão de Corte Masculino",
    variationName: "Urbano & Lifestyle",
    title: "Estilo com Atitude",
    subtitle: "Muito mais que uma barbearia, um ponto de encontro para quem valoriza o visual.",
    badge: "Corte Moderno",
    badgeIcon: "Star",
    primaryButton: "Marcar Agora",
    secondaryButton: "Nossa Unidade",
    bgImage: "https://images.unsplash.com/photo-1585747860715-2ba37e788b70?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#000000",
    badgeColor: "#18181b",
    badgeTextColor: "#ffffff",
    fontFamily: "syne",
    titleSize: "lg"
  },
  {
    id: "barbearia-3",
    niche: "Salão de Corte Masculino",
    variationName: "Forte & Marcante",
    title: "O CORTE QUE VOCÊ RESPEITA",
    subtitle: "Cortes de elite e barba feita com toalha quente. Experiência premium para o homem moderno.",
    badge: "Elite Barbers",
    badgeIcon: "Award",
    primaryButton: "Agendar Agora",
    secondaryButton: "Ver Galeria",
    bgImage: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#450a0a",
    badgeColor: "#fef2f2",
    badgeTextColor: "#450a0a",
    fontFamily: "bebas",
    titleSize: "xl"
  },

  // 6. MAQUIADORA
  {
    id: "maquiadora-1",
    niche: "Maquiadora",
    variationName: "Social & Eventos",
    title: "Sua Beleza em Evidência",
    subtitle: "Maquiagem profissional para noivas, eventos e ensaios fotográficos.",
    badge: "Make Profissional",
    badgeIcon: "Star",
    primaryButton: "Pedir Orçamento",
    secondaryButton: "Portfólio",
    bgImage: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#db2777",
    badgeColor: "#fdf2f8",
    badgeTextColor: "#9d174d",
    fontFamily: "lora",
    titleSize: "md"
  },
  {
    id: "maquiadora-2",
    niche: "Maquiadora",
    variationName: "Editorial & Artística",
    title: "O Poder da Transformação",
    subtitle: "Crie looks impactantes e conceituais para editoriais de moda e produções audiovisuais.",
    badge: "Expert Artist",
    badgeIcon: "Sparkles",
    primaryButton: "Trabalhe Conosco",
    secondaryButton: "Ver Editorial",
    bgImage: "https://images.unsplash.com/photo-1512496011951-a6994413c2ca?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#701a75",
    badgeColor: "#fae8ff",
    badgeTextColor: "#4a044e",
    fontFamily: "syne",
    titleSize: "lg"
  },
  {
    id: "maquiadora-3",
    niche: "Maquiadora",
    variationName: "Moderno & Clean",
    title: "Realce sua Beleza Natural",
    subtitle: "Maquiagem 'no-makeup' look e técnicas de iluminação para um visual fresco e sofisticado.",
    badge: "Natural Look",
    badgeIcon: "Heart",
    primaryButton: "Agendar Make",
    secondaryButton: "Ver Antes/Depois",
    bgImage: "https://images.unsplash.com/photo-1522335994033-501d66866b8b?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#be185d",
    badgeColor: "#fdf2f8",
    badgeTextColor: "#be185d",
    fontFamily: "montserrat",
    titleSize: "xl"
  },

  // 7. STUDIOS DE TATUAGENS
  {
    id: "tattoo-1",
    niche: "Studio de Tatuagem",
    variationName: "Artístico & Autoral",
    title: "Sua História na sua Pele",
    subtitle: "Artistas especializados em diversos estilos, garantindo segurança e arte de alta qualidade.",
    badge: "Arte Única",
    badgeIcon: "Flower2",
    primaryButton: "Agendar Sessão",
    secondaryButton: "Artistas",
    bgImage: "https://images.unsplash.com/photo-1598136490941-30d885318abd?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#000000",
    badgeColor: "#18181b",
    badgeTextColor: "#ffffff",
    fontFamily: "syne",
    titleSize: "md"
  },
  {
    id: "tattoo-2",
    niche: "Studio de Tatuagem",
    variationName: "Dark & Minimalista",
    title: "Expressão em Tinta",
    subtitle: "Blackwork, Fine Line e Pontilhismo. Onde a precisão encontra a criatividade.",
    badge: "Especialista Fine Line",
    badgeIcon: "Award",
    primaryButton: "Pedir Orçamento",
    secondaryButton: "Flash Tattoo",
    bgImage: "https://images.unsplash.com/photo-1560707303-4e980ce876ad?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#27272a",
    badgeColor: "#f4f4f5",
    badgeTextColor: "#18181b",
    fontFamily: "sans",
    titleSize: "lg"
  },
  {
    id: "tattoo-3",
    niche: "Studio de Tatuagem",
    variationName: "Impacto & Visual",
    title: "ARTE QUE NÃO SE APAGA",
    subtitle: "Realismo e Neotradicional de alto nível. Transformamos suas ideias em obras primas na pele.",
    badge: "Top Artists",
    badgeIcon: "Star",
    primaryButton: "Orçamento WhatsApp",
    secondaryButton: "Portfólio",
    bgImage: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#09090b",
    badgeColor: "#ffffff",
    badgeTextColor: "#09090b",
    fontFamily: "bebas",
    titleSize: "xl"
  },

  // 8. PSICOLOGIA
  {
    id: "psicologia-1",
    niche: "Psicologia",
    variationName: "Acolhedor & Terapêutico",
    title: "Espaço de Acolhimento",
    subtitle: "Terapia individual para adultos e adolescentes em um ambiente seguro e ético.",
    badge: "Saúde Mental",
    badgeIcon: "Smile",
    primaryButton: "Marcar Consulta",
    secondaryButton: "Sobre a Terapia",
    bgImage: "https://images.unsplash.com/photo-1527137342181-19aab11a8ee1?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#4f46e5",
    badgeColor: "#eef2ff",
    badgeTextColor: "#3730a3",
    fontFamily: "serif",
    titleSize: "md"
  },
  {
    id: "psicologia-2",
    niche: "Psicologia",
    variationName: "Moderno & Prático",
    title: "Sua Jornada de Autoconhecimento",
    subtitle: "Terapia online e presencial focada em resultados e bem-estar emocional diário.",
    badge: "Psicologia Clínica",
    badgeIcon: "Heart",
    primaryButton: "Agendar Conversa",
    secondaryButton: "Como Funciona",
    bgImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#312e81",
    badgeColor: "#e0e7ff",
    badgeTextColor: "#1e1b4b",
    fontFamily: "sans",
    titleSize: "lg"
  },
  {
    id: "psicologia-3",
    niche: "Psicologia",
    variationName: "Evolução & Clareza",
    title: "Mente Sã, Vida Plena",
    subtitle: "Abordagem cognitiva para superar desafios e encontrar equilíbrio em todas as áreas da vida.",
    badge: "Bem-estar Mental",
    badgeIcon: "Sun",
    primaryButton: "Começar Terapia",
    secondaryButton: "Áreas de Atuação",
    bgImage: "https://images.unsplash.com/photo-1516302752625-fbbad0eb0643?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e40af",
    badgeColor: "#eff6ff",
    badgeTextColor: "#1e40af",
    fontFamily: "lora",
    titleSize: "xl"
  },

  // 9. PERSONAL TRAINER
  {
    id: "personal-1",
    niche: "Personal Trainer",
    variationName: "Performance & Resultados",
    title: "Transforme seu Corpo",
    subtitle: "Treinos personalizados de acordo com seus objetivos, com acompanhamento profissional constante.",
    badge: "Foco no Objetivo",
    badgeIcon: "Sun",
    primaryButton: "Consultoria Online",
    secondaryButton: "Ver Planos",
    bgImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#ea580c",
    badgeColor: "#fff7ed",
    badgeTextColor: "#9a3412",
    fontFamily: "montserrat",
    titleSize: "md"
  },
  {
    id: "personal-2",
    niche: "Personal Trainer",
    variationName: "High Tech & Atleta",
    title: "Supere seus Limites",
    subtitle: "Metodologia avançada para atletas e iniciantes que buscam a máxima performance física.",
    badge: "Elite Training",
    badgeIcon: "Crown",
    primaryButton: "Começar Agora",
    secondaryButton: "Metodologia",
    bgImage: "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e2937",
    badgeColor: "#f3f4f6",
    badgeTextColor: "#111827",
    fontFamily: "syne",
    titleSize: "xl"
  },
  {
    id: "personal-3",
    niche: "Personal Trainer",
    variationName: "Força & Impacto",
    title: "SEU CORPO, SEU TEMPLO",
    subtitle: "Treinamento de força e hipertrofia com foco em resultados reais e duradouros.",
    badge: "Hardcore Training",
    badgeIcon: "Award",
    primaryButton: "Agendar Treino",
    secondaryButton: "Ver Depoimentos",
    bgImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#c2410c",
    badgeColor: "#fff7ed",
    badgeTextColor: "#c2410c",
    fontFamily: "bebas",
    titleSize: "xl"
  },

  // 10. CLINICAS DE FISIOTERAPIA
  {
    id: "fisioterapia-1",
    niche: "Clínicas de Fisioterapia",
    variationName: "Reabilitação & Cuidado",
    title: "Recuperação com Excelência",
    subtitle: "Tratamentos especializados em reabilitação motora e alívio de dores crônicas.",
    badge: "Fisioterapia Especializada",
    badgeIcon: "Heart",
    primaryButton: "Agendar Avaliação",
    secondaryButton: "Especialidades",
    bgImage: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#0891b2",
    badgeColor: "#ecfeff",
    badgeTextColor: "#0e7490",
    fontFamily: "sans",
    titleSize: "md"
  },
  {
    id: "fisioterapia-2",
    niche: "Clínicas de Fisioterapia",
    variationName: "Pilates & Movimento",
    title: "Vida sem Limitações",
    subtitle: "Pilates clínico e RPG para melhorar sua postura, flexibilidade e qualidade de vida.",
    badge: "Pilates e RPG",
    badgeIcon: "Sun",
    primaryButton: "Aula Experimental",
    secondaryButton: "Conheça o Studio",
    bgImage: "https://images.unsplash.com/photo-1518459031867-a89b944bffe4?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#0d9488",
    badgeColor: "#f0fdfa",
    badgeTextColor: "#0f766e",
    fontFamily: "lora",
    titleSize: "lg"
  },
  {
    id: "fisioterapia-3",
    niche: "Clínicas de Fisioterapia",
    variationName: "Inovação & Recuperação",
    title: "Movimente-se com Liberdade",
    subtitle: "Fisioterapia esportiva e tecnologia para atletas e pacientes de alta performance.",
    badge: "Fisioterapia 4.0",
    badgeIcon: "Gem",
    primaryButton: "Marcar Avaliação",
    secondaryButton: "Tratamentos",
    bgImage: "https://images.unsplash.com/photo-1530026405186-ed1f139313f8?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#0369a1",
    badgeColor: "#f0f9ff",
    badgeTextColor: "#0369a1",
    fontFamily: "space",
    titleSize: "xl"
  },

  // 11. CONSULTORIAS E ACESSORIAS
  {
    id: "consultoria-1",
    niche: "Consultoria e Assessoria",
    variationName: "Corporativo & Estratégico",
    title: "Soluções para seu Negócio",
    subtitle: "Ajudamos empresas a crescerem com processos eficientes e gestão de alta performance.",
    badge: "Consultoria Estratégica",
    badgeIcon: "Crown",
    primaryButton: "Falar com Consultor",
    secondaryButton: "Nossos Cases",
    bgImage: "https://images.unsplash.com/photo-1454165833767-027ffea7028c?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e3a8a",
    badgeColor: "#eff6ff",
    badgeTextColor: "#1e40af",
    fontFamily: "sans",
    titleSize: "md"
  },
  {
    id: "consultoria-2",
    niche: "Consultoria e Assessoria",
    variationName: "Finanças & Investimento",
    title: "Gestão Inteligente",
    subtitle: "Planejamento financeiro e tributário para maximizar a lucratividade da sua empresa.",
    badge: "Consultoria Financeira",
    badgeIcon: "Award",
    primaryButton: "Diagnóstico Grátis",
    secondaryButton: "Serviços",
    bgImage: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#166534",
    badgeColor: "#f0fdf4",
    badgeTextColor: "#166534",
    fontFamily: "montserrat",
    titleSize: "lg"
  },
  {
    id: "consultoria-3",
    niche: "Consultoria e Assessoria",
    variationName: "Tech & Digital",
    title: "O Futuro é Agora",
    subtitle: "Transformação digital e inovação para negócios que querem dominar o mercado.",
    badge: "Digital Strategy",
    badgeIcon: "Sparkles",
    primaryButton: "Agendar Mentoria",
    secondaryButton: "Ver Soluções",
    bgImage: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e1b4b",
    badgeColor: "#e0e7ff",
    badgeTextColor: "#1e1b4b",
    fontFamily: "space",
    titleSize: "xl"
  },

  // 12. ADVOCACIA
  {
    id: "advocacia-1",
    niche: "Advocacia",
    variationName: "Tradicional & Sólido",
    title: "Defesa e Compromisso Ético",
    subtitle: "Assessoria jurídica especializada para garantir seus direitos com agilidade e transparência.",
    badge: "Escritório de Advocacia",
    badgeIcon: "Award",
    primaryButton: "Consulta Jurídica",
    secondaryButton: "Áreas de Atuação",
    bgImage: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#451a03",
    badgeColor: "#fef3c7",
    badgeTextColor: "#92400e",
    fontFamily: "serif",
    titleSize: "md"
  },
  {
    id: "advocacia-2",
    niche: "Advocacia",
    variationName: "Direito Digital & Moderno",
    title: "Justiça na Era Digital",
    subtitle: "Proteção jurídica especializada para negócios online, startups e tecnologia.",
    badge: "Direito Digital",
    badgeIcon: "Star",
    primaryButton: "Falar com Advogado",
    secondaryButton: "Especialidades",
    bgImage: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e2937",
    badgeColor: "#f3f4f6",
    badgeTextColor: "#111827",
    fontFamily: "montserrat",
    titleSize: "lg"
  },
  {
    id: "advocacia-3",
    niche: "Advocacia",
    variationName: "Premium & Exclusivo",
    title: "Excelência em Defesa Jurídica",
    subtitle: "Soluções jurídicas personalizadas para questões complexas e alta gestão patrimonial.",
    badge: "Assessoria VIP",
    badgeIcon: "Crown",
    primaryButton: "Agendar Reunião",
    secondaryButton: "Nossa Equipe",
    bgImage: "https://images.unsplash.com/photo-1453723490680-8b9d7350dd93?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#18181b",
    badgeColor: "#f4f4f5",
    badgeTextColor: "#18181b",
    fontFamily: "lora",
    titleSize: "xl"
  },

  // 13. FOTOGRAFIA
  {
    id: "fotografia-1",
    niche: "Fotografia",
    variationName: "Artístico & Sensível",
    title: "Eternizando Momentos",
    subtitle: "Ensaios fotográficos e cobertura profissional com olhar sensível e artístico.",
    badge: "Fotografia de Família",
    badgeIcon: "Star",
    primaryButton: "Ver Orçamentos",
    secondaryButton: "Galeria",
    bgImage: "https://images.unsplash.com/photo-1493863641943-9b68992a8d07?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#111827",
    badgeColor: "#f3f4f6",
    badgeTextColor: "#1f2937",
    fontFamily: "lora",
    titleSize: "md"
  },
  {
    id: "fotografia-2",
    niche: "Fotografia",
    variationName: "Moda & Comercial",
    title: "Impacto Visual",
    subtitle: "Fotografia publicitária e de moda de alto nível para destacar sua marca no mercado.",
    badge: "Fashion Photographer",
    badgeIcon: "Gem",
    primaryButton: "Trabalhe Conosco",
    secondaryButton: "Ver Portfólio",
    bgImage: "https://images.unsplash.com/photo-1533109721025-d1ae7ee7c1e1?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#000000",
    badgeColor: "#18181b",
    badgeTextColor: "#ffffff",
    fontFamily: "syne",
    titleSize: "xl"
  },
  {
    id: "fotografia-3",
    niche: "Fotografia",
    variationName: "Clean & Moderno",
    title: "A Arte do Clique",
    subtitle: "Minimalismo e técnica para fotos que transmitem emoção e clareza.",
    badge: "Studio Pro",
    badgeIcon: "Sparkles",
    primaryButton: "Agendar Ensaio",
    secondaryButton: "Ver Estilos",
    bgImage: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#27272a",
    badgeColor: "#f4f4f5",
    badgeTextColor: "#27272a",
    fontFamily: "space",
    titleSize: "xl"
  },

  // 14. PROFESSORES PARTICULARES
  {
    id: "professores-1",
    niche: "Professores Particulares",
    variationName: "Escolar & Acadêmico",
    title: "Aprenda com Qualidade",
    subtitle: "Aulas particulares de reforço escolar e idiomas para todas as idades.",
    badge: "Reforço Escolar",
    badgeIcon: "Smile",
    primaryButton: "Aula Experimental",
    secondaryButton: "Disciplinas",
    bgImage: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#16a34a",
    badgeColor: "#f0fdf4",
    badgeTextColor: "#166534",
    fontFamily: "sans",
    titleSize: "md"
  },
  {
    id: "professores-2",
    niche: "Professores Particulares",
    variationName: "Música & Artes",
    title: "Desperte seu Talento",
    subtitle: "Aulas de piano, violão e canto com professores graduados e experientes.",
    badge: "Escola de Música",
    badgeIcon: "Star",
    primaryButton: "Agendar Aula",
    secondaryButton: "Instrumentos",
    bgImage: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#7c3aed",
    badgeColor: "#f5f3ff",
    badgeTextColor: "#6d28d9",
    fontFamily: "lora",
    titleSize: "lg"
  },
  {
    id: "professores-3",
    niche: "Professores Particulares",
    variationName: "Impacto & Conhecimento",
    title: "DOMINE NOVAS HABILIDADES",
    subtitle: "Cursos intensivos e mentoria para quem busca evolução rápida e consistente.",
    badge: "Mentoria de Elite",
    badgeIcon: "Crown",
    primaryButton: "Quero Aprender",
    secondaryButton: "Ver Planos",
    bgImage: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#1e3a8a",
    badgeColor: "#eff6ff",
    badgeTextColor: "#1e3a8a",
    fontFamily: "bebas",
    titleSize: "xl"
  },

  // 15. ESCOLAS DE DANÇA
  {
    id: "danca-1",
    niche: "Escola de Dança",
    variationName: "Clássico & Acadêmico",
    title: "Arte em Movimento",
    subtitle: "Aulas de ballet clássico e jazz para formação de bailarinos profissionais.",
    badge: "Ballet e Jazz",
    badgeIcon: "Sparkles",
    primaryButton: "Agendar Aula Teste",
    secondaryButton: "Modalidades",
    bgImage: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#9333ea",
    badgeColor: "#faf5ff",
    badgeTextColor: "#7e22ce",
    fontFamily: "serif",
    titleSize: "md"
  },
  {
    id: "danca-2",
    niche: "Escola de Dança",
    variationName: "Urbano & Contemporâneo",
    title: "Sinta o Ritmo",
    subtitle: "Hip hop, Dança Contemporânea e Danças de Salão. Expresse-se através da dança.",
    badge: "Danças Urbanas",
    badgeIcon: "Star",
    primaryButton: "Quero Dançar",
    secondaryButton: "Horários",
    bgImage: "https://images.unsplash.com/photo-1535525153412-5a42439a210d?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#c026d3",
    badgeColor: "#fdf4ff",
    badgeTextColor: "#c026d3",
    fontFamily: "syne",
    titleSize: "lg"
  },
  {
    id: "danca-3",
    niche: "Escola de Dança",
    variationName: "Moderno & Tech",
    title: "Dance Sem Fronteiras",
    subtitle: "Aulas híbridas e tecnologia aplicada à dança. Venha para a nova era do movimento.",
    badge: "Modern Dance",
    badgeIcon: "Gem",
    primaryButton: "Inscrever-se",
    secondaryButton: "Ver Vídeos",
    bgImage: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?q=80&w=1920&auto=format&fit=crop",
    bgType: "image",
    primaryButtonColor: "#4f46e5",
    badgeColor: "#eef2ff",
    badgeTextColor: "#4f46e5",
    fontFamily: "space",
    titleSize: "xl"
  }
];
